Fix multiple consecutive payments of a single expense report
Dolibarr/dolibarr pull request #21785
Opened 2022-08-17 23:56 UTC by ymollard

# FIX | Multiple consecutive payments of a single expense report

Since they are from table `expensereport`, columns `total_ht` and `total_ttc` are already the sum of the whole expense report, no need to sum. The sum was causing wrong reports when the payment is made of several consecutive payments.

2022-08-18 21:01 UTC, eldy requested changes

2022-08-18 21:01 UTC, eldy commented on htdocs/compta/resultat/clientfourn.php
> +				$sql = "SELECT p.rowid, p.ref, u.rowid as userid, u.firstname, u.lastname, date_format(pe.datep,'%Y-%m') as dm, p.total_ht as amount_ht, p.total_ttc as amount_ttc";
I agree to remove the SUM in line 1041 because in mode CREANCE-DETTE we want the amount if expense report. But on line 1050, mode RECETTE-DEPENSE, we want the amount paid, so we need the SUM but what we must fix for line 1051 is keeping the SUM but use the field in pe table (the sub table of payments that need the sum to have the group by ok) instead of the field in p table. Can you check ?

2022-08-19 23:54 UTC, ymollard commented on htdocs/compta/resultat/clientfourn.php
> +				$sql = "SELECT p.rowid, p.ref, u.rowid as userid, u.firstname, u.lastname, date_format(pe.datep,'%Y-%m') as dm, p.total_ht as amount_ht, p.total_ttc as amount_ttc";
Yes, but the way to do it does not look obvious to me. Let's take an example where the expense report has 2 lines with different VATs and 2 incomplete payments :

![image](https://user-images.githubusercontent.com/3295098/185720424-181f19a0-6177-4d2d-bffa-36b39fb1a74c.png)


The TTC amount for RECETTE-DEPENSE is `sum(amount)` (here, 220+5 = 225) but how do we deduce the HT amount? 
Here under is an extract of the data coming from the selection at line 1050 (1) to help:

|rowid|ref        |entity|ref_number_int|ref_ext|total_ht    |total_tva  |localtax1 |localtax2 |total_ttc   |multicurrency_code|multicurrency_tx|multicurrency_total_ht|multicurrency_total_tva|multicurrency_total_ttc|amount      |fk_typepayment|num_payment|note|fk_bank|fk_user_creat|fk_user_modif|id |entity|code|libelle |type|active|accountancy_code|module|position|rowid|ref        |userid|firstname|lastname|dm     |amount_ht   |amount_ttc  |
|-----|-----------|------|--------------|-------|------------|-----------|----------|----------|------------|------------------|----------------|----------------------|-----------------------|-----------------------|------------|--------------|-----------|----|-------|-------------|-------------|---|------|----|--------|----|------|----------------|------|--------|-----|-----------|------|---------|--------|-------|------------|------------|
|10   |ER2208-0007|1     |NULL          |NULL   |200.00000000|29.00000000|0.00000000|0.00000000|229.00000000|NULL              |1.00000000      |0.00000000            |0.00000000             |0.00000000             |220.00000000|2             |           |    |121    |12           |NULL         |2  |1     |VIR |Virement|2   |1     |NULL            |NULL  |0       |10   |ER2208-0007|12    |Alice    |Adminson|2022-08|200.00000000|229.00000000|
|10   |ER2208-0007|1     |NULL          |NULL   |200.00000000|29.00000000|0.00000000|0.00000000|229.00000000|NULL              |1.00000000      |0.00000000            |0.00000000             |0.00000000             |5.00000000  |2             |           |    |123    |12           |NULL         |2  |1     |VIR |Virement|2   |1     |NULL            |NULL  |0       |10   |ER2208-0007|12    |Alice    |Adminson|2022-08|200.00000000|229.00000000|

(1) : `SELECT *, p.rowid, p.ref, u.rowid as userid, u.firstname, u.lastname, date_format(pe.datep,'%Y-%m') as dm, sum(p.total_ht) as amount_ht, sum(p.total_ttc) as amount_ttc FROM llx_expensereport as p INNER JOIN llx_user as u ON u.rowid=p.fk_user_author INNER JOIN llx_payment_expensereport as pe ON pe.fk_expensereport = p.rowid LEFT JOIN llx_c_paiement as c ON pe.fk_typepayment = c.id WHERE p.entity IN (1) AND p.fk_statut>=5 AND pe.datep >= '2022-04-01 00:00:00' AND pe.datep <= '2023-03-31 23:59:59' GROUP BY u.rowid, p.rowid, p.ref, u.firstname, u.lastname, dm, pe.rowid`

2022-08-22 11:34 UTC, eldy commented on htdocs/compta/resultat/clientfourn.php
> +				$sql = "SELECT p.rowid, p.ref, u.rowid as userid, u.firstname, u.lastname, date_format(pe.datep,'%Y-%m') as dm, p.total_ht as amount_ht, p.total_ttc as amount_ttc";
When we are in mode "RECETTE-DEPENSE", the amount without tax (HT) has no sense. We should never show it on screen in this mode. This mode "RECETTE-DEPENSE" is to report real payments done (so without meaning of HT and TTC).
With mode "CREANCES-DETTES", we can show both the amount with tax TTC and without tax HT.
So for the payment mode, we can use the same value "sum(pe.amount)" for both HT and TTC so the sql still works and return something but later we should not reuse the field HT.

2022-08-22 16:44 UTC, ymollard commented on htdocs/compta/resultat/clientfourn.php
> +				$sql = "SELECT p.rowid, p.ref, u.rowid as userid, u.firstname, u.lastname, date_format(pe.datep,'%Y-%m') as dm, p.total_ht as amount_ht, p.total_ttc as amount_ttc";
OK, this is done and it looks fixed according to the test here above.

2022-08-23 14:01 UTC, merged