Add OpenID Connect impl
Dolibarr/dolibarr pull request #22741
Opened 2022-11-03 15:45 UTC by jeritiana

# NEW #22740

2022-11-04 08:29 UTC, hregis commented
@jeritiana Thank you for this contribution, but on the other hand when do you check the existence of the user in Dolibarr?

2022-11-04 09:02 UTC, jeritiana commented
@hregis I don't check the existence of the user inside this module (or at least I didn't think I had to) because it is already handled somewhere else downstream. From my understanding of the [authentication documentation](https://wiki.dolibarr.org/index.php?title=Authentication), the goal of the login modules is to check the validity of a couple user/password. In the case of OpenID, this is delegated to the OpenID Identity Provider.
Which brings us to the following sequence:
1. The user provides his credentials login/password to the OpenID provider
2. This module checks from the OpenID provider if the authentication went well
3. If the authentication fails: the error message is displayed (e.g. Bad login/password)
  If the authentication succeeds on the OpenID provider: this module returns the login value to the calling function.
  Later, if the user (i.e the returned login) does **not** exist in Dolibarr, the error message "Unable to find user xxx" is displayed.

2022-11-04 09:08 UTC, hregis commented
@jeritiana yes but you don't check the existence of the user in Dolibarr !

2022-11-04 09:09 UTC, hregis commented
@jeritiana you can check the existing openid login method https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/login/functions_openid.php

2022-11-04 09:28 UTC, jeritiana commented
@hregis Okay I see what you mean. Isn't this already the purpose of [main.inc.php#L869](https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/main.inc.php#L869), leading to "User not found, connexion refused" and `ErrorCantLoadUserFromDolibarrDatabase`? i.e. to check the existence of the user in Dolibarr?

Or should we also add this check inside an authentication module?

2022-11-04 09:33 UTC, hregis commented
@jeritiana in my opinion it is better to check if the user exists and is "active" before querying OpenID. In addition it will be necessary to add compatibility with Multicompany, this I can take care of.

2022-11-04 09:33 UTC, hregis commented
@jeritiana and why not have improved the OpenID login method already existing in Dolibarr?

2022-11-04 09:47 UTC, jeritiana commented
> @jeritiana in my opinion it is better to check if the user exists and is "active" before querying OpenID. In addition it will be necessary to add compatibility with Multicompany, this I can take care of.

Sure enough, let's try that. I will let you know of any progression. Thanks for taking care of the Multicompany compatibility.

> @jeritiana and why not have improved the OpenID login method already existing in Dolibarr?

Because the already existing login method is fully featured for OpenID 2.0. Modifying would be a breaking change for Dolibarr and there would be impacts on users, compared to adding a new next gen OpenID Connect support.

2022-11-16 11:08 UTC, battosai30 commented
Line 49 there is an error I think : 
(GETPOSTISSET['code']) 
should be
(GETPOSTISSET('code'))

2022-11-16 12:31 UTC, battosai30 commented on htdocs/core/login/functions_openid_connect.php
> +		dol_syslog("functions_openid_connect::check_user_password_openid_connect /token=".print_r($token_response, true), LOG_DEBUG);
$token_response = getURLContent($conf->global->MAIN_AUTHENTICATION_OIDC_TOKEN_URL, 'POST', http_build_query($auth_param),1, array(),array('http', 'https'),2);
=> allow local identity provider (in my case, I use virtual machines on the same network so 192.168.xx.xx and it's blocked)

2022-11-22 14:40 UTC, FlorentPoinsaut requested changes

2022-11-22 14:40 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +	} elseif (GETPOSTISSET['code']) {
```suggestion
	} elseif (GETPOSTISSET('code')) {
```

2022-11-22 14:40 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +						'redirect_uri'  => $conf->global->MAIN_AUTHENTICATION_OIDC_REDIRECT_URL
```suggestion
			'redirect_uri'  => $conf->global->MAIN_AUTHENTICATION_OIDC_REDIRECT_URL
```

2022-11-22 14:40 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +			if (array_key_exists($login_claim, $userinfo_content)) {
> PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, stdClass given in /var/www/html/core/login/functions_openid_connect.php:79

```suggestion
			if (property_exists($userinfo_content, $login_claim)) {
```

2022-11-22 15:23 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +		if ($token_content->access_token) {
```suggestion
		if (property_exists($token_content, 'access_token')) {
```

2022-11-22 15:56 UTC, FlorentPoinsaut requested changes
Check if the user exists as in the original openid method

2022-11-22 15:56 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +	global $conf;
```suggestion
	global $db, $conf, $langs;
```

2022-11-22 15:56 UTC, FlorentPoinsaut commented on htdocs/core/login/functions_openid_connect.php
> +				$_SESSION["dol_loginmesg"] = "";
```suggestion
				$sql = 'SELECT login, entity, datestartvalidity, dateendvalidity';
				$sql .= ' FROM '.MAIN_DB_PREFIX.'user';
				$sql .= " WHERE login = '".$userinfo_content->$login_claim."'";
				$sql .= ' AND entity IN (0,'.(array_key_exists('dol_entity', $_SESSION) ? ((int) $_SESSION["dol_entity"]) : 1).')';
	
				dol_syslog("functions_openid::check_user_password_openid", LOG_DEBUG);
				$resql = $db->query($sql);
				if ($resql) {
					$obj = $db->fetch_object($resql);
					if ($obj) {
						$now = dol_now();
						if ($obj->datestartvalidity && $db->jdate($obj->datestartvalidity) > $now) {
							// Load translation files required by the page
							$langs->loadLangs(array('main', 'errors'));
							$_SESSION["dol_loginmesg"] = $langs->transnoentitiesnoconv("ErrorLoginDateValidity");
							return '--bad-login-validity--';
						}
						if ($obj->dateendvalidity && $db->jdate($obj->dateendvalidity) < dol_get_first_hour($now)) {
							// Load translation files required by the page
							$langs->loadLangs(array('main', 'errors'));
							$_SESSION["dol_loginmesg"] = $langs->transnoentitiesnoconv("ErrorLoginDateValidity");
							return '--bad-login-validity--';
						}
	
						$login = $obj->login;
					}
				}
```

2023-01-13 16:12 UTC, FlorentPoinsaut commented
Hi @jeritiana 
Do you want to continue to maintain this PR or would you prefer that I create a new one?
Thank you in advance,

2023-01-17 16:09 UTC, jeritiana commented
Hi @FlorentPoinsaut , I will have a look and integrate the suggested changes. Thanks for the ping!

2023-04-13 15:56 UTC, philippe-opendsi commented
Hi, 
For the impatient, we have put this PR in a module available here. 
https://git.open-dsi.fr/dolibarr-extension/openidconnect
Working with us with a Lemon-LDAP
ping @eldy 
Regards

2023-04-13 20:40 UTC, eldy commented
Thanks @jeritiana 
Can you describe as a comment how we can test this (when startikg from nothing) ?

2023-04-13 21:04 UTC, merged