New add sort and separation for objects linked
Dolibarr/dolibarr pull request #26566
Opened 2023-11-13 10:01 UTC by atm-sami

# NEW
- add sort and separation for objects linked

2023-12-06 14:15 UTC, atm-sami commented
@eldy

2024-08-21 07:38 UTC, atm-thibaultf commented
@eldy

2024-08-21 08:54 UTC, atm-maxime commented
@eldy

2024-08-21 11:12 UTC, eldy requested changes

2024-08-21 11:12 UTC, eldy commented on htdocs/bom/tpl/linkedobjectblock.tpl.php
> +	if (count($linkedObjectBlock) > 1 || !empty($conf->global->LINKED_OBJECTS_HAVE_ALWAYS_SUBTOTAL)) {
conf->global->xxx is now forbidden. Can you replace with getDolGlobalString('xxx') ?

Also it seems pr is chanching the user interface, can you provide a screenshot to show the result after the change ?

2024-08-21 14:37 UTC, samifilali commented
Before
![Before](https://github.com/user-attachments/assets/88de5dc2-4142-4697-bda3-0c7cb6273a8b)

After
![After](https://github.com/user-attachments/assets/1f7cea5f-6a81-43cd-b42c-ab9f9d9567c3)

2024-08-21 14:38 UTC, samifilali reviewed
Done

2024-09-20 14:51 UTC, atm-thibaultf commented
@eldy

2026-07-16 11:58 UTC, closed without merging