Input select from foraign keys
Dolibarr/dolibarr pull request #28425
Opened 2024-02-26 00:34 UTC by leninrivas

# NEW|New [*input select from foraign key*]
[*Module builder create dictionaries from foraign keys with select of array.*]

2024-02-26 00:43 UTC, mdeweerd commented on htdocs/admin/dict.php
> +			$isforaign = false;
Spelling: isforeign

2024-02-26 01:06 UTC, leninrivas commented on htdocs/admin/dict.php
> +			$isforaign = false;
Fixed, Thanks

2024-02-26 14:30 UTC, eldy commented
Can you paste a screenshot of what the feature brings ?

2024-02-26 17:06 UTC, leninrivas commented
> Can you paste a screenshot of what the feature brings ?

This is.
![dictionaryfk](https://github.com/Dolibarr/dolibarr/assets/53640168/2388bab1-85c8-4cb6-a5f6-76ccf7807460)

2024-04-16 20:34 UTC, eldy requested changes

2024-04-16 20:34 UTC, eldy commented on htdocs/admin/dict.php
> +			$tablef = 'c_'.$fieldelement;
This may hang for dictionnaries with field fk_xxx where xxx does not match zny tables, like
fk_pays, fk_region, fk_departement, fk_variable, fk_parent, fk_account,...
I suggest to add a test to show the selectbox only for the fk_... you need to manage....

2025-10-04 11:33 UTC, eldy commented
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

2025-10-04 11:33 UTC, closed without merging