Fix check if object is null
Dolibarr/dolibarr pull request #29872
Opened 2024-06-07 09:09 UTC by lamrani002

# FIX|Fix phan warning

2024-06-07 14:35 UTC, eldy commented
What was thz warning code ?

2024-06-08 11:50 UTC, lamrani002 commented
Property CommonDocGenerator::$extrafieldsCache (ExtraFields) in empty() is not falsy.

2024-06-08 15:16 UTC, eldy requested changes

2024-06-08 15:16 UTC, eldy commented on htdocs/core/class/commondocgenerator.class.php
> -		if (empty($this->extrafieldsCache)) {
Try with if (!is_object...

2024-07-18 00:20 UTC, eldy commented
Pr has meege conflict, surely because of fix already meeged differently. So i close pr.

2024-07-18 00:21 UTC, closed without merging