FIX : Missing hook in getElementProperties
Dolibarr/dolibarr pull request #29870
Opened 2024-06-07 08:48 UTC by atm-irvine

#FIX|Fix Missing hook in getElementProperties
I added the missing hook in getElementProperties to handle $element_properties array because of some errors for permissions

2024-06-07 14:39 UTC, eldy requested changes

2024-06-07 14:39 UTC, eldy commented on htdocs/core/lib/functions.lib.php
> +	$reshook = $hookmanager->executeHooks('changeElementProperties', $parameters);
Can youbrename trigger function in getElementProperties to match same name than dolibarr function.

2024-06-17 14:28 UTC, atm-john commented
@eldy this PR allow fix some troubles for modules discribed in [#29369 ](https://github.com/Dolibarr/dolibarr/issues/29369)

2024-06-17 14:38 UTC, eldy requested changes

2024-06-17 14:38 UTC, eldy commented on htdocs/core/lib/functions.lib.php
> +		setEventMessages($hookmanager->error, $hookmanager->errors, 'errors');
The method is getElementProperties is low level method that can be run out of user/web context (in cron job for exemple).
So we should not have setEventMessage inside.

2024-06-19 12:37 UTC, atm-john commented
close this PR and use #30086 instead

2024-06-19 12:38 UTC, closed without merging