Support Docker install in production environment
Dolibarr/dolibarr pull request #29951
Opened 2024-06-09 08:07 UTC by yledoare

- Enable dolibarr_main_url_root writable in forced mode (needed for reverse proxy)
- Add install.forced.docker.php
- Move old docker files in docker-dev folder
- Fix else if CodeSniffer warning

2024-06-09 10:02 UTC, eldy requested changes

2024-06-09 10:02 UTC, eldy commented on htdocs/install/fileconf.php
> +	/* Behind a reverse proxy with https, we have to keep it writable */
I suggest to replace test 
if !empty(force_install_no_edit)
With 
If !empty(force_install_no_edit) && force_install_no_edit != 3

So you can use value 3 in your config file...

2024-06-15 08:15 UTC, yledoare reviewed
revert on main_url editable

2024-06-15 08:15 UTC, yledoare commented on htdocs/install/fileconf.php
> +	/* Behind a reverse proxy with https, we have to keep it writable */
Thanks but if I create the value 3 for force_install_no_edit, I will need to make many other changes in other files
I will make a new PR for Docker in Prod without changing this file, then a new one specific for the  force_install_no_edit mode

2024-06-15 15:11 UTC, merged