Patch noncounting stock
Dolibarr/dolibarr pull request #30199
Opened 2024-06-29 21:49 UTC by DaBootO

CLOSE https://github.com/Dolibarr/dolibarr/issues/26384 Implement STATUS_OPENEXT_ALL for use of non-counting warehouses e.g. quarantine

This feature complements the need explained in #26384 and the implementation of the STATUS_OPENEXT_ALL warehouse type. With the changes a warehouse can be used e.g. as a quarantine warehouse or a temporary pre-QC warehouse. The status "Open (omitted from stock calculation)" keeps the definition vague enough as not to constrain the use of this status too much in the sense of "either quarantine or pre-QC".
For code-readability and convenience the change is using the load_stock and loadWarehouses implementation. As the option of warehouseclosed, warehouseopen and warehouseinternal is already introduced in the code we can piggyback ride with the introduction of the STATUS_OPENEXT_ALL onto the product list view, stock transfer, delivery selection etc.

2024-06-30 10:16 UTC, eldy requested changes

2024-06-30 10:16 UTC, eldy commented on htdocs/product/class/product.class.php
> +				$warehouseStatus[Entrepot::STATUS_OPENEXT_ALL] = Entrepot::STATUS_OPENEXT_ALL;
Using OPENEXT_ALL as a status of stock (at same level than open and closed stock) is not a good idea. Because the status of warehouse define if we can do stock movement or not. It does not mean if we want to include it into stock calculation or not. A warehouse can be closed (so no movement allowed) but we may want or not include it in stock calculation).
So i removed the todo on STATUS_OPENEXT_ALL
Instead there is another property called warehouse_usage that you can use to include or exclude stock from calculation.

I modified the code to show the way.
If you enable option STOCK_USE_WAREHOUSE_USAGE to 1, then you have the property warehouse_usage that is enabled.
Value 1=include in stock, 2=exclude.

We miss the implementation of the case 2...

2024-06-30 11:54 UTC, DaBootO commented on htdocs/product/class/product.class.php
> +				$warehouseStatus[Entrepot::STATUS_OPENEXT_ALL] = Entrepot::STATUS_OPENEXT_ALL;
Hello eldy,

OK I reverted all the changes in the PR and I am currently working on the implementation of the warehouse_usage variable.

Thanks for the review!

2024-07-01 18:36 UTC, DaBootO commented on htdocs/product/class/product.class.php
> +				$warehouseStatus[Entrepot::STATUS_OPENEXT_ALL] = Entrepot::STATUS_OPENEXT_ALL;
@eldy I pushed a new commit which introduces the functionality you recommended.

2024-07-06 10:58 UTC, DaBootO commented
I am very sorry! I am pretty new to PRs and how my local developments is being reflected in this PR timeline. Sorry for clogging up stuff with all those name changes and pulling the new develop branch from upstream -.-

2024-07-12 08:09 UTC, lmag commented
Thank you for this very good first proposition 👍 
Traduction should be change like this :

- Entrepôt Interne -> Inclus dans le stock disponible
- Entrepôt externe) -> Exclus du stock disponible
- Utilisation de entrepôt -> Fonction Entrepot

2024-07-12 09:48 UTC, DaBootO commented
> Thank you for this very good first proposition 👍 Traduction should be change like this :
> 
> * Entrepôt Interne -> Inclus dans le stock disponible
> * Entrepôt externe) -> Exclus du stock disponible
> * Utilisation de entrepôt -> Fonction Entrepot

Thank you very much! I changed the translation keys in the en_US version as to CONTRIBUTING.md
Hope this was correct

2025-03-10 16:24 UTC, lmag commented
@DaBootO 
any news about your PR ?

2025-03-10 16:27 UTC, DaBootO commented
> @DaBootO 
> any news about your PR ?

Well tbh I do not know if I still have to do sth or if the merge is only in eldy's hands.

Do you think there is a way to bump this?

2025-03-10 18:43 UTC, lmag commented
Some checks were not successful so eldy will never merge in this case may you update your pr ?

2025-03-12 00:19 UTC, DaBootO commented
@lmag I tried my best to fix all the CI errors but now I get some (to me it seems) unrelated errors in the ExportTest::testExportModulesDatasets test.
**It says the table "llx_commandefournisseur" does not exist. Well.**

I am not quite sure and too tired to search for what causes it.

**As I am new to all this: Would a unrelated error stop this PR from ever merging?
And while we are at it: Is it bad practice to do little amends to the PR to fix all CI errors or is there a way to use the CI/CD Pipeline locally to not clog up this projects actions?**

Sorry for not being able to fix it.

2025-03-12 08:31 UTC, altairis-noe commented
Hello, @DaBootO, the error is, indeed, not yours, as it originates in `htdocs/exports/class/export.class.php:732` which refers to `llx_commandefournisseur` instead of `llx_commande_fournisseur`, and you did not touch that file !

It seems that the export of supplier orders categories is broken, but I am not sure how to fix it, and we will have to ask @eldy to intervene here!

2025-03-17 08:12 UTC, altairis-noe commented
Hello again @DaBootO,
It seems that conflicts have appeared here. I hope that once you resolve them, the checks will pass 🤞🏻

2025-03-20 23:38 UTC, DaBootO commented
@lmag @altairis-noe Sorry for the late reply! I did not find time until now for the fix. Was a simple GETPOST to GETPOSTINT. I learn with every line I change.

Thank you for being a helping hand in this endeavor!

2025-03-21 08:38 UTC, altairis-noe commented
Indeed @DaBootO: Dolibarr is a never ending learning curve 😇 
Thanks and 👏🏻

2025-12-13 06:12 UTC, Pichinov-Jose commented
Hi @eldy 
Do you know what has to be done in this PR?

2025-12-13 07:04 UTC, eldy commented
> Hi @eldy 
> Do you know what has to be done in this PR?
> 

Yes, the pr has conflict with other changes done by other pr. So a merge must be done on the branch used to make the pr.  conflicts solve, and a push must be redone once conflict is solved.

A second point is that code $conf->global->xxx must bexreplaced with getDolGlobalConst('xxx')

Also the pr seems to introduce a duplicate feature (added option WAREHOUSE_INTERNAL and WAREHOUSE_EXTERNAL are duplicates of option already implemented with USAGE_INTERNAL and  USAGE_EXTERNAL).

2025-12-14 07:15 UTC, josett225 commented
Ok I will review it deeply

2026-07-16 11:58 UTC, closed without merging