Retroport: NEW determine multi-currency price on object line create tpl (#28021)
Dolibarr/dolibarr pull request #30535
Opened 2024-08-02 15:23 UTC by altairis-benjamin

Related to the PR #30473 but with a clean commit.

2024-08-08 08:12 UTC, lvessiller-opendsi commented
Sorry, but you put "NEW" in the title of this PR and it seems to be a FIX.
I follow the related PR and the Issue.
The fix is only on rounding high quantities or is when you use a different currency between the added product and the supplier order ?

2024-08-09 09:25 UTC, BenjaminFlr commented
I changed the title, but I juste copied/pasted the original PR title.

In fact, currently, when you add a product on a supplier order, the price taken into account is the one in your own currency.
The price in its original currency is computed from the price in your currency which is multiplicated by the rate and, because of rounded values, the price in the supplier's currency can be wrong, which can cause problems on orders.

With this fix, the price in its original currency is used to calculate all prices: the price in supplier's currency is the good one, and the one in your currency is also correct.

2024-08-12 13:15 UTC, lvessiller-opendsi requested changes

2024-08-12 13:15 UTC, lvessiller-opendsi commented on htdocs/core/tpl/objectline_create.tpl.php
> +				if (multicurrency_code == undefined) { multicurrency_code = jQuery('#idprodfournprice').attr('data-multicurrency-code'); }  	// When select is done from HTML input with ajax autocomplete
Why to use here "== undefined" and not "typeof multicurrency_code === 'undefined'" like in other parts of this JS script ?

2024-08-18 15:37 UTC, altairis-benjamin commented on htdocs/core/tpl/objectline_create.tpl.php
> +				if (multicurrency_code == undefined) { multicurrency_code = jQuery('#idprodfournprice').attr('data-multicurrency-code'); }  	// When select is done from HTML input with ajax autocomplete
Only because it's a back port of an existing PR. Maybe this change should also be done in develop?

2024-09-06 12:56 UTC, lvessiller-opendsi commented on htdocs/core/tpl/objectline_create.tpl.php
> +				if (multicurrency_code == undefined) { multicurrency_code = jQuery('#idprodfournprice').attr('data-multicurrency-code'); }  	// When select is done from HTML input with ajax autocomplete
Yes, I think.
@eldy What is your advice ?

2024-09-12 06:43 UTC, rycks approved these changes
seems ok for me (note: but i don't have multicurrency setup so i can't make real tests)

2024-09-12 07:42 UTC, lvessiller-opendsi approved these changes

2024-09-18 01:11 UTC, eldy commented
> seems ok for me (note: but i don't have multicurrency setup so i can't make real tests)

Some PR are difficult to validate without testing it. So you should have environment in v18 dedicated to validate PR. I recommand to have one environment per version with similar data, so if a trouble occurs in v18, you can compare easily with v17 or V18.
This is for example how i work: I created just one virual host the point to the directory git will all cloned versions and i load on the database of all of them the initdemo sql file so data are same.
![image](https://github.com/user-attachments/assets/df2bf203-0093-4869-b9cb-22b6e278c33d)

2024-09-18 01:19 UTC, eldy commented on htdocs/core/tpl/objectline_create.tpl.php
> +				if (multicurrency_code == undefined) { multicurrency_code = jQuery('#idprodfournprice').attr('data-multicurrency-code'); }  	// When select is done from HTML input with ajax autocomplete
As we are in a v18, and it is a backport, code must be the much as possible similar than original,even if code is not "clean", being "already validated" into a higher version has priority.

2024-09-18 01:22 UTC, merged