Qual: Fix phan notifications for compta/facture/card
Dolibarr/dolibarr pull request #30667
Opened 2024-08-18 23:24 UTC by mdeweerd

# Qual: Fix phan notifications for compta/facture/card

Disable ignores for compta/facture/card.php and fix notices.

2024-08-19 00:51 UTC, mdeweerd commented
@eldy 
Only a few things left.

The main question about these lines where $remise_percent  and  $dateinvoice are undefined is: should the be fetched with GETPOST or not?

https://github.com/Dolibarr/dolibarr/blob/fcfd39b4ce9c36c65a3b3d214903442c8908bf41/htdocs/compta/facture/card.php#L3240-L3246

2024-09-29 10:44 UTC, mdeweerd commented
@eldy I've ignored the PhanUndeclaredProperty notice again so that this PR can be integrated - I think that the remaining ones were introduced since I started this PR.

2024-09-29 14:18 UTC, eldy requested changes

2024-09-29 14:18 UTC, eldy commented on htdocs/compta/facture/card.php
> +				'@phan-var-force Facture|Commande $expesrc';
I think the type of object in this case is Expedition

2024-10-13 22:02 UTC, mdeweerd commented
@eldy 
I added the dol_syslog statement to the code to log the class type so that you can check it yourself by visiting `compta/facture/card.php?action=create&origin=shipping&originid=2&socid=18` from the test database an check the log file contents.

2024-11-07 04:10 UTC, merged