FIX : To have only the sender's entity when sending mail
Dolibarr/dolibarr pull request #31053
Opened 2024-09-20 07:43 UTC by Thomas905

2024-09-26 08:04 UTC, lvessiller-opendsi commented
Thanks for your contribution.
First, you should fix the indentation code and commit again to resolve the pre-commit errors.
For me, it's not obvious to understand this FIX without description.
Could you give us more details and how to reproduce ?

Concerning the filter for user entity in SQL request, it's recommended  to use "getEntity('user')" instead of "(0, $conf->entity)".
@hregis, is it right ?

2024-09-26 08:18 UTC, hregis commented
@lvessiller-opendsi @Thomas905 this is a dictionary

getEntity('c_email_senderprofile')

2024-10-03 07:16 UTC, rycks requested changes
waiting for same solution as @hregis and @lvessiller-opendsi  :-)
i discover that getentity can work with dictionnary

please update your commit :)

2024-10-10 07:36 UTC, rycks commented
@Thomas905 could you please update your PR ?

2025-01-20 08:29 UTC, eldy commented
@rycks @lvessiller-opendsi When a PR has no answer like this one after a long time and when the change to to is minor, we can do the change ourself from the github interface directly by using the "Edit file" available on tab "Files changed":
![image](https://github.com/user-attachments/assets/c590548d-f11d-4993-8e09-21b19bdb9e82)

Do you have permission to use this feature ?

2025-01-20 08:37 UTC, rycks commented
Hello @eldy 
i don't have that super power :-)

![image](https://github.com/user-attachments/assets/6b0c64a4-d1c6-4f8e-83c2-783a16487dde)

2025-01-20 12:32 UTC, lvessiller-opendsi commented
@eldy 
I have the same rights as @rycks and I can't edit the file.

2025-07-17 23:36 UTC, eldy commented
It seems that github has recently modified the permissions to do the edit. 
@rycks, @lvessiller-opendsi  Still not able to make the change from github Edit link ?

2025-08-07 07:14 UTC, lvessiller-opendsi approved these changes

2025-10-01 17:18 UTC, merged