NEW : add fichinter category - define new table
Dolibarr/dolibarr pull request #31234
Opened 2024-10-02 13:37 UTC by defrance

2024-10-28 00:36 UTC, eldy requested changes

2024-10-28 00:36 UTC, eldy commented on htdocs/install/mysql/tables/llx_categorie_fichinter.key.sql
> +-- ============================================================================
Can you rename the file llx_categorie_fichinter-fichinter so table is created only when module fichinter is enabled.

2024-10-28 00:36 UTC, eldy commented on htdocs/install/mysql/tables/llx_categorie_fichinter.sql
> +-- ============================================================================
Can you rename the file llx_categorie_fichinter-fichinter so table is created only when module fichinter is enabled.

2024-10-29 13:47 UTC, defrance commented on htdocs/install/mysql/tables/llx_categorie_fichinter.sql
> +-- ============================================================================
change name made on the 2 files

2024-10-29 13:49 UTC, defrance commented
@eldy what is the good way to inform you when i made change asked? I have the impression that the information is not reaching you and that my PRs then remain indefinitely forgotten.

2024-10-30 22:04 UTC, eldy commented
> @eldy what is the good way to inform you when i made change asked? I have the impression that the information is not reaching you and that my PRs then remain indefinitely forgotten.

No need to inform.
PR are stacked in the pull of open PR to be processed every month.

Note that due to a high number of PR of new features merged compared to a very very low number of PR contributions to stabilize application and fix bugs, PR for new features have low priority.

2024-11-13 21:44 UTC, merged