FIX: Fix return value of hook sendMail when hook return -1 who must be return false in sendfile() function
Dolibarr/dolibarr pull request #31460
Opened 2024-10-18 12:27 UTC by kkhelifa-opendsi

Fix return value of hook sendMail when hook return -1 who must be return false in sendfile() function

2024-10-18 12:28 UTC, kkhelifa-opendsi commented
Fixed in develop

2024-10-31 08:40 UTC, rycks commented
ok, maybe enhance that PR : please have a look at line 1209 and 1226 of the same file with returns other things that a boolean :)

2024-10-31 08:40 UTC, rycks requested changes
ok, maybe enhance that PR : please have a look at line 1209 and 1226 of the same function with returns other things that a boolean :)

2024-10-31 08:50 UTC, lvessiller-opendsi reviewed
Maybe complete with https://github.com/Dolibarr/dolibarr/commit/8bf54dee9ea7acb16a6d6c6140516caf0655d429

2025-01-20 08:23 UTC, merged