FIX : Position class select inactive users
Dolibarr/dolibarr pull request #32092
Opened 2024-11-25 15:53 UTC by atm-irvine

# FIX|Fix Position class select inactive users
Previously, it was possible to select inactive users from the position list.
A configuration option, USER_HIDE_INACTIVE_IN_COMBOBOX, exists and allows you to control whether inactive users are hidden or visible in dropdown menus. To ensure this configuration works as intended, I changed the select type to select_dolusers for the position_list, and removed the constraint from the fields.

2024-11-25 19:52 UTC, eldy requested changes

2024-11-25 19:52 UTC, eldy commented on htdocs/hrm/class/position.class.php
> +		$form = new Form($db);
Can you do global $form and do an new only if defined, to avoid to instabtiate n times this global object.

2024-11-26 08:13 UTC, atm-irvine commented
@eldy I've been taking care of your returns

2024-11-26 08:19 UTC, hregis commented
@atm-irvine remove global $db and use $this->db please

2024-11-26 08:47 UTC, atm-irvine commented
@hregis Thank you for your suggestion. It should be okay now.

2024-11-29 13:53 UTC, eldy commented on htdocs/hrm/class/position.class.php
> +		$form ??= new Form($this->db);
This code is not compatible with php 7.1.  You can use more human reabable  and more secured code  like
```
if (! $form instanceOf Form) {
      $form = new Form($this->db);
}
```

2024-11-29 14:00 UTC, atm-irvine commented on htdocs/hrm/class/position.class.php
> +		$form ??= new Form($this->db);
Should be okay now

2024-12-19 06:38 UTC, atm-irvine commented
@eldy Is it ok for you?

2024-12-19 17:52 UTC, eldy commented
> @eldy Is it ok for you?

Can you remind me on which screen or page you need to have all users in combo list ?

2024-12-20 07:13 UTC, atm-irvine commented
@eldy It's on position_list.php
A customer wants the possibility (like it was done before), to filter active and inactive users (employees)

2025-01-30 22:11 UTC, closed without merging