FIX: #5640
Dolibarr/dolibarr pull request #5754
Opened 2016-09-15 05:01 UTC by olsesacl

This error persists in Dolibarr 4.0.

I edit files that are in different directory in Dolibarr 4.0.
If I have to create another pull request to that let me know and I think other with editions for that version

Delete 

> $cancel     = GETPOST('cancel','alpha');

It hasn't any funcion really, because in loop if else use for example:

> else if ($action == 'updateline' && $user->rights->ficheinter->creer && **GETPOST('cancel')**)

2016-09-17 15:52 UTC, eldy commented on htdocs/comm/propal.php
> -	if ($cancel) $action = '';
Can you keep this.
For future, we must change code to follow this rule that is much secured than adding a test && ! GETPOST('cancel') on each following test

2016-09-17 15:52 UTC, eldy commented on htdocs/commande/card.php
> -	if ($cancel) $action='';
Can you keep this.
For future, we must change code to follow this rule that is much secured than adding a test && ! GETPOST('cancel') on each following test

2016-09-17 15:53 UTC, eldy requested changes

2016-09-17 15:54 UTC, eldy commented
Yes, can you also submit a fix for 4.0 (but keep usage of cancel that is cleared at beginning of "action area".

2016-10-24 11:38 UTC, olsesacl commented
@eldy , changed correctly?

2016-11-11 13:45 UTC, eldy commented
No.
The ligne
if ($cancel) $action='';
that is a securit to clear vaue of action if we click on a cancel has still disappears.

2017-01-07 19:28 UTC, eldy commented
What about version 4.0.3 ?

2019-05-03 09:45 UTC, eldy commented
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...

2019-05-03 09:45 UTC, closed without merging