FIX : Reserved SQL Word not allowed as extrafield
Dolibarr/dolibarr pull request #5996
Opened 2016-11-15 13:57 UTC by defrance

Alternative bugfix of https://github.com/Dolibarr/dolibarr/pull/5991
seems better
@atm-florian : can you fill the postgres variant side?

2016-11-16 10:55 UTC, ghost requested changes

2016-11-16 10:55 UTC, atm-florian commented on htdocs/core/actions_extrafields.inc.php
> +			}
$res = $db->query($sql);
 +				if ($res)
 +					while ($rec = $db->fetch_array($res)) {
 +						$cats[] = $rec['word'];}

2016-11-16 10:55 UTC, atm-florian commented on htdocs/core/actions_extrafields.inc.php
> +				$sql="SELECT * FROM pg_get_keywords()";
SELECT * FROM pg_get_keywords() WHERE catcode='R'

2016-11-19 20:06 UTC, eldy commented on htdocs/core/actions_extrafields.inc.php
> +				$sql ="SELECT name as reservedword FROM mysql.help_keyword";
This are system table.
And the database user, if server setup was done correctly won't have access to such tables.
A hardcoded list of common keys should be used even if it does not prevent 100% of cases.

2019-05-03 09:43 UTC, eldy commented
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

2019-05-03 09:43 UTC, closed without merging