Pdf azur
Dolibarr/dolibarr pull request #8320
Opened 2018-03-09 22:21 UTC by frederic34

2018-04-11 10:10 UTC, atm-john commented
Hi,

I curently work on an equivalent goal for invoice and i just saw yours. It can be usefull  to uniform.
Curently I review with my team worker to add last needed hooks on my version.

My curent working branch : https://github.com/atm-john/dolibarr/tree/NEW_PDF_DOCUMENT_COLUMN

Show changes : https://github.com/Dolibarr/dolibarr/compare/develop...atm-john:NEW_PDF_DOCUMENT_COLUMN

2018-04-11 19:29 UTC, frederic34 commented
@atm-john 
you can check what i have done and tell me if i need to close this PR

in french:
la note publique peut s'étendre sur plusieurs pages, les grilles sont dessinées à la fin
la largeur des colonnes n'est pas fixée et s'adapte si il y a des remises, des images etc et s'adapte au format de page(a4, us, etc)
il reste des défauts

2018-04-12 19:33 UTC, anacronox requested changes
Hi it's @atm-john 

After testing I found some weird behaviors : 
.Lines table position for empty and short public note.
.Title row doesn't appear on empty, short and medium public note.
.An empty page is added on long public note

[long note .pdf](https://github.com/Dolibarr/dolibarr/files/1904627/long.note.pdf)
[medium note.pdf](https://github.com/Dolibarr/dolibarr/files/1904628/medium.note.pdf)
[no note.pdf](https://github.com/Dolibarr/dolibarr/files/1904629/no.note.pdf)
[short note.pdf](https://github.com/Dolibarr/dolibarr/files/1904630/short.note.pdf)

2018-04-12 19:33 UTC, anacronox commented on htdocs/core/modules/propale/doc/pdf_azur.modules.php
> +                foreach ($arraynotegrids as $key => $grid) {
On action adding line you will have a warning like " Invalid argument supplied for foreach()  " because $arraynotegrids will not be set.

2018-04-12 20:05 UTC, atm-john commented
Hi (I comme back with my good ID ;-) )
when the public note is long, the pagination behaves better with your solution compared to the current model, I'm currently looking at how to integrate the pagination with long notes. I come back to you as soon as I have something new on "crabe pdf". In the meantime, I created the "pull request #8570" to give visibility to the development version for crab pdf. I invite you to consult and comment my code.

Regards.

2018-04-13 14:39 UTC, frederic34 commented
@atm-john 
As you can see, row width is not fixed in mm, but have a weight, so page can be a4, us letter, it adapts.

2018-04-14 17:11 UTC, frederic34 commented
Did some progress...
[PR1712-0001.pdf](https://github.com/Dolibarr/dolibarr/files/1910646/PR1712-0001.pdf)
[(PROV2).pdf](https://github.com/Dolibarr/dolibarr/files/1910647/PROV2.pdf)

2018-04-16 18:44 UTC, atm-john commented
Hi, 
in #8570 I have extend my dev to AZUR and EINSTEIN

2018-04-16 22:38 UTC, closed without merging